name: npm-publish
on:
  push:
  workflow_dispatch:
jobs:
  npm-publish:
    if: github.repository == 'volantis-x/volantis-static'
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: "Automated Version Bump"
        run: |
          node npm-version-bump.js
      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_mhuig_token }}
